#
#  @(#) $Id: Makefile.config,v 1.6 2004/09/04 16:17:50 honda Exp $
# 

#
#  Makefile のシステム依存部分（Solution Engine用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS) \
			-I$(SRCDIR)/pdic/simple_sio
COPTS    := $(COPTS) -m3
LDFLAGS  := $(LDFLAGS) 

#
# カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)\
				:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o fdc37c935a.o 


#
#  各セグメントの開始アドレスの定義
#
ifeq ($(DBGENV),GDB_STUB)
     TEXT_START_ADDRESS=0x0C003000
     DATA_START_ADDRESS=0x0C100000
else
     TEXT_START_ADDRESS=0x0C000000
     DATA_START_ADDRESS=0x0C100000
endif

#
#  ターゲットボード依存の定義
#

# MS7729RSE01
CDEFS := $(CDEFS)  -DMS7729RSE01

# MS7709ASE01
#CDEFS := $(CDEFS) -DMS7709ASE01

# MS7750SE01
#CDEFS := $(CDEFS) -DMS7750SE01


#
#  エンディアン
#
#Little
COPTS := $(COPTS) -ml 
LDFLAGS := $(LDFLAGS) -ml
LDSCRIPT = $(CPU)/shlelf.ld

#Big
#COPTS := $(COPTS) -mb 
#LDFLAGS := $(LDFLAGS) -mb
#LDSCRIPT = $(CPU)/shelf.ld

