#
#  Makefile のシステム依存部分（DMT33401用）
#

#
#  データエリアポインタ数
#
DP_CNT = 1

#
#  ディレクトリの定義
#
TOPDIR = ../..
LIBDIR = $(TOPDIR)/lib/pe
INCDIR = $(TOPDIR)/include

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)-$(TOOL)/$(SYS) \
		-I$(SRCDIR)/config/$(CPU)/$(SYS) -I$(INCDIR)
CDEFS := $(CDEFS) -DTPS_DAREA_CNT=$(DP_CNT)
COPTS := $(COPTS) -B$(TOPDIR)/ -mdp=$(DP_CNT) -mc33pe
LDFLAGS := $(LDFLAGS) -L$(LIBDIR)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)-$(TOOL)/$(SYS)
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o

#
#  スタートアップモジュールに関する定義
#

# スタートアップモジュールのオブジェクトファイル名
START_OBJS = sys_start.o

# スタートアップモジュールのコンパイルルール
$(START_OBJS): %.o: %.c
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

# スタートアップモジュールの依存関係作成ルール
$(START_OBJS:.o=.d): %.d: %.c
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend

#
#   リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/dmt33e07.ld

