# 
#   TOPPERS/JSP Kernel
#       Toyohashi Open Platform for Embedded Real-Time Systems/
#       Just Standard Profile Kernel
#  
#   Copyright (C) 2000-2005 by Embedded and Real-Time Systems Laboratory
#                               Toyohashi Univ. of Technology, JAPAN
#  
#   上記著作権者は，以下の (1)〜(4) の条件か，Free Software Foundation 
#   によって公表されている GNU General Public License の Version 2 に記
#   述されている条件を満たす場合に限り，本ソフトウェア（本ソフトウェア
#   を改変したものを含む．以下同じ）を使用・複製・改変・再配布（以下，
#   利用と呼ぶ）することを無償で許諾する．
#   (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#       権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#       スコード中に含まれていること．
#   (2) 本ソフトウェアを，ライブラリ形式など，他のソフトウェア開発に使
#       用できる形で再配布する場合には，再配布に伴うドキュメント（利用
#       者マニュアルなど）に，上記の著作権表示，この利用条件および下記
#       の無保証規定を掲載すること．
#   (3) 本ソフトウェアを，機器に組み込むなど，他のソフトウェア開発に使
#       用できない形で再配布する場合には，次のいずれかの条件を満たすこ
#       と．
#     (a) 再配布に伴うドキュメント（利用者マニュアルなど）に，上記の著
#         作権表示，この利用条件および下記の無保証規定を掲載すること．
#     (b) 再配布の形態を，別に定める方法によって，TOPPERSプロジェクトに
#         報告すること．
#   (4) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#       害からも，上記著作権者およびTOPPERSプロジェクトを免責すること．
#  
#   本ソフトウェアは，無保証で提供されているものである．上記著作権者お
#   よびTOPPERSプロジェクトは，本ソフトウェアに関して，その適用可能性も
#   含めて，いかなる保証も行わない．また，本ソフトウェアの利用により直
#   接的または間接的に生じたいかなる損害に関しても，その責任を負わない．
#  
#

#
#   Makefile のプロセッサ依存部（Xstormy16用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = xstormy16-elf

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
#     デバッグ時には、-O0や-Wallを指定することで、コンパイル時や
#     やEVAデバッガ中で、より詳細な情報を取得することができます。
#COPTS := $(COPTS) -g -O0 -Wall
#     デバッグ終了後は、-DNDEBUGを指定することで、カーネル中から
#     デバッグのためのコードを取り除くことができます。(user.txt参照)
COPTS := $(COPTS) -g -O2 
CDEFS := $(CDEFS) -DNDEBUG

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o hw_serial.o hw_timer.o cpu_stdio.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend

#
#  アセンブラからCの構造体にアクセスするためのoffset.hを依存部で用意
#
OMIT_MAKEOFFSET = YES

#
#  実行ファイルの拡張子の指定
#
OBJEXT = elf

#
#  開発環境の指定
#
DEVENV := EVA_DEBUGGER

