/* This file is generated by genoffset. */

#define TCB_sp	24
#define TCB_pc	28
#define TCB_enatex	12
#define TCB_texptn	16
#ifdef __LittleEndian
#define TCB_enatex_mask 0x40000
#else
#define TCB_enatex_mask 0x2000
#endif
