#
#@(#) $Id: Makefile.config,v 1.10 2007/01/05 02:02:38 honda Exp $
# 

#
#  Makefile のプロセッサ依存 (ARMv4アーキテクチャー用)
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = arm-elf

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
COPTS    := $(COPTS)  -O2 


#
#  カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR) $(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) cpu_config.o


#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
        -O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
