#
#  Makefile のプロセッサ依存 (H8S用)
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = h8300-hms

#
#  コンパイルオプション
#
INCLUDES	:= $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
COPTS		:= $(COPTS) -g -ms -mint32 -mrelax -O2 -DLABEL_ASM

#H8S/2600対応版（積和レジスタのサポート ; cpu_support.S）
# (テストしていません。)
#COPTS		:= $(COPTS) -ms2600 -DH8S_2600

#ノーマルモード用
# (テストしていません。)
#COPTS		:= $(COPTS) -mn -DH8S_NORMAL_MODE

#
#  カーネルに関する定義
#
KERNEL_DIR	:= $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS	:= $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS	:= $(KERNEL_COBJS) cpu_config.o h8s_sci.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS := $(START_OBJS) start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
