#
#  Makefile のプロセッサ依存 (S1C33用)
#

#
#  ターゲットアーキテクチャの定義
#
ARCH = s1c33-epson-elf

#
#  ディレクトリの定義
#

#
#  コンパイラドライバの定義
#
CC = $(ARCH)-gcc
AS = $(ARCH)-as
LD = $(ARCH)-ld
AR = $(ARCH)-ar
NM = $(ARCH)-nm
RANLIB = $(ARCH)-ranlib
OBJCOPY = $(ARCH)-objcopy
OBJDUMP = $(ARCH)-objdump

#
#  コンパイルフラグ
#
COPTS := -gstabs -Wall -fno-common -O -mgda=0 -mlong-calls 

#
#  デフォルトコンパイルルールの定義
#
%.o: %.c
	$(CC) -c $(CFLAGS) $<

%.s: %.c
	$(CC) -S $(CFLAGS) $<

