#
#  Makefile のシステム依存部分（VR5500, RTE-VR5500-CB用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = mipsel-nec-elf

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS) \
			-I$(SRCDIR)/pdic/simple_sio
COPTS := $(COPTS) -mgp32
LDFLAGS := $(LDFLAGS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS) \
				:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o tl16pir552.o
# tl16pir552.o は、ボード搭載シリアルコントローラ関係のオブジェクトファイル

#
#  リンカスクリプトの定義
#
#LDSCRIPT = $(CPU)/$(SYS)/vr5500_elf.ld

#ROM に無条件ジャンプを入れたときに使う。
LDSCRIPT = $(CPU)/$(SYS)/vr5500_elf_ram.ld

