#
#  Makefile のシステム依存部分（DMT33209用）
#

#
#  データエリアポインタ数
#
DP_CNT = 1

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
CDEFS := $(CDEFS) -DTPS_DAREA_CNT=$(DP_CNT)
COPTS := $(COPTS) -mdp=$(DP_CNT)
LDFLAGS := $(LDFLAGS) 

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o

#
#  スタートアップモジュールに関する定義
#

# スタートアップモジュールのオブジェクトファイル名
START_OBJS = sys_start.o

# スタートアップモジュールのコンパイルルール
$(START_OBJS): %.o: %.c
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

# スタートアップモジュールの依存関係作成ルール
$(START_OBJS:.o=.d): %.d: %.c
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend

#
#   リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/dmt33209.ld

