#
#  @(#) $Id: Makefile.config,v 1.2 2004/05/26 19:14:24 honda Exp $
# 

#
#  Makefile のシステム依存部分（INTEGRATOR用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm9tdmi -Wa,--gstabs 
LDFLAGS  := $(LDFLAGS) -mcpu=arm9tdmi  -N 

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o integrator.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/integrator.ld


#
#  ターゲットボード依存の定義
#

#  INTEGRATOR用
COPTS   := $(COPTS) -DINTEGRATOR -mlittle-endian   
LDFLAGS := $(LDFLAGS) -mlittle-endian 
#TEXT_START_ADDRESS=0x1000003c
TEXT_START_ADDRESS=0x10800000
DATA_START_ADDRESS=0x10810000

#TEXT_START_ADDRESS=0x00000000
#DATA_START_ADDRESS=0x00810000
