#
#  Makefile のシステム依存部分（H8S/2350 用）
#

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS := $(COPTS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = exception_vector.o

#
#  リンカスクリプトの定義
#
ifeq ($(DBGENV), GDB_STUB)
	LDSCRIPT = $(CPU)/$(SYS)/h8s_coff_gdb.ld
else
	LDSCRIPT = $(CPU)/$(SYS)/h8s_coff.ld
endif

#
#  例外処理ベクタテーブルモジュールに関する定義 (将来拡張用)
#
$(EXCVTBL_ASMOBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(EXCVTBL_ASMOBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
