#
#  @(#) $Id: Makefile.config,v 1.4 2004/05/02 08:21:02 honda Exp $
# 

#
#  Makefile のシステム依存部分（MIRE-MULTI用）
#


#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS    := $(COPTS)    -mno-xl-soft-mul -mno-xl-soft-div  -mxl-barrel-shift
LDFLAGS  := $(LDFLAGS) 

LIBS    := $(LIBS) -lc_hard_shift


#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o 


#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0400
DATA_START_ADDRESS=0x9000
#TEXT_START_ADDRESS=0xF1100000
#DATA_START_ADDRESS=0xF1180000

