CROSS=c33-epson-elf-
CC=$(CROSS)gcc
AS=$(CROSS)gcc
LD=$(CROSS)ld
AR=$(CROSS)ar
OBJCOPY=$(CROSS)objcopy

LDFLAGS=-static -s --no-gc-sections -N -L$(LIBDIR)
CFLAGS=-Wall -I. -I../../mini-libc/include/ -gstabs -mlong-calls -fno-builtin -Os -mc33pe -DNO_GZIP
ASFLAGS=-c -xassembler-with-cpp -Wa,--gstabs -medda32 -mc33pe -mc33_ext

ZLIB_INFLATE = \
    inflate.o \
    inffast.o \
    inftrees.o \
    trees.o \
    zutil.o


TARGETS=libz.a
all: $(TARGETS)

.c.o:
	$(CC) -M $(CFLAGS) $< > $(<:.c=.d)
	$(CC) $(CFLAGS) -c $< -o $(<:.c=.o)

libz.a: $(ZLIB_INFLATE)
	$(AR) q libz.a $^

clean::
	rm -rf $(TARGETS) *.o *.elf *.d

-include $(wildcard *.d) dummy

