#
#  @(#) $Id: Makefile.config,v 1.5 2003/12/11 06:47:39 honda Exp $
# 

#
#  Makefile のシステム依存部分（MS7717CP01用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS) \
			-I$(SRCDIR)/pdic/simple_sio
COPTS := $(COPTS)  -ml -m3
LDFLAGS := $(LDFLAGS)  -ml
DBGENV :=

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)\
				:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o st16c2550.o


#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x8C003000
DATA_START_ADDRESS=0x8C100000

#
#  リンカスクリプト
#
LDSCRIPT = $(CPU)/shlelf.ld







