#
#  Makefile のシステム依存部分（VR4131用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = mipsel-nec-elf

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS := $(COPTS) -msoft-float -mgp32
LDFLAGS := $(LDFLAGS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o vr4131_dsiu.o

#
#  リンカスクリプトの定義
#

#LDSCRIPT = $(CPU)/$(SYS)/vr4131elf.ld

ifeq ($(DBGENV),GDB_STUB)
	LDSCRIPT = $(CPU)/$(SYS)/vr4131_elf_gdb.ld
else
	LDSCRIPT = $(CPU)/$(SYS)/vr4131_elf.ld
endif
