"""
 Parse the spacing-file generated by extract_image.py

 Copyright (C) 2009 Holger Hans Peter Freyther <zecke@openmoko.org>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

class SpacingEntry:
    def __init__(self, left, right, x, y):
	self.left = left
	self.right = right
	self.x = x
	self.y = y

def load(file):
    glyphs = {} 
    for line in file:
	(glyph_pair, spacing) = line.rsplit(": ", 2)	
	(glyph_left, glyph_right) = glyph_pair.split("-", 2)
	(spacing_x, spacing_y) = spacing.split(",", 2)
	if not glyph_left in glyphs:
	    glyphs[glyph_left] = []

	if glyph_right in glyphs[glyph_left]:
	    print "Incorrect spacing... %s %s %s" % (glyph_left, glyph_right, file)

	glyphs[glyph_left].append(SpacingEntry(
		int(glyph_left), int(glyph_right),
		int(spacing_x), int(spacing_y)))

    return glyphs
