#
#  Makefile のシステム依存部分
#  (株)中央製作所製μITRON搭載SH1CPUボード用
#
#


#
#  実行環境の定義
#
#      DBGENVには下記の中の１つだけを選択する。
#
#　　　DBGENV = ROMはROM化である（他の実行環境ではない）ことを
#　　　明示しているだけで、ソースコード中で参照はしていない。
#
#　　　共通部Makefileでデフォルトの実行環境としてGDB stubが選択される。
#　　　DBGENV=GDB_STUBに仮設定された状態で、このファイルが読み込まれる。
#　　　
#　　　DBGENV = PARTNERはROMICE使用時にNMIまでのROMベクタテーブルを
#　　　ベクタベースレジスタのエリアへ転送する
#
DBGENV = ROM
#DBGENV = PARTNER

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)

COPTS := $(COPTS)
LDFLAGS := $(LDFLAGS) -Wl,-Map,jsp.map

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS)
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o sys_support.o sh1sci2.o 


#
#  マクロ定義オプション
#


#
#  各セグメントの開始アドレスの定義
#

# GDB stubの場合
ifeq ($(DBGENV),GDB_STUB)
	# テキストセクションの先頭番地
	# stubが使用するメモリ領域の後ろ
	TEXT_START_ADDRESS=0x2010d00

	# RAM領域の先頭アドレス
	# 　textセクションのすぐ後ろに配置するので定義する必要なし
else
# ROM化の場合
	# テキストセクションの先頭番地
	# ユーザーＲＯＭ 領域の開始
	TEXT_START_ADDRESS=0x00010000

	# RAM領域の先頭アドレス
	# エリア2：外部ＳＲＡＭ
	DATA_START_ADDRESS=0x02000000
endif

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld

