#
#  @(#) $Id: Makefile.config,v 1.6 2003/07/16 09:12:41 honda Exp $
# 

#
#	Makefile のターゲット依存部（Linux用）
#

#
#  カーネルに関する定義
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU) 
COPTS    := $(COPTS) -g -O2  

#
#  カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR) $(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) 
KERNEL_COBJS   := $(KERNEL_COBJS) cpu_config.o sys_config.o start.o

#
# makeoffset は不必要
#
OMIT_MAKEOFFSET = true
