#
#  @(#) $Id: Makefile.config,v 1.1 2004/09/03 16:39:56 honda Exp $
# 

#
#	Makefile のプロセッサ依存部（PowerPC用）
#

#
#  ターゲットアーキテクチャの定義
#      powerpc-elf-gcc以外のコンパイラを用いる場合は
#      $(SYS)/Makefile.configで変数TARGETを定義する。
#　　　定義されていない場合は、デフォルトでTARGETに
#　　　powerpc-elfが設定される。
#
ifndef TARGET
   TARGET = powerpc-elf
endif

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
COPTS := $(COPTS) -Wall -O2

# PowerPCはC言語のシンボルに_が付かないので、-DLABEL_ASMはいらない


#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
# 未完成
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
