#
#  Makefile のプロセッサ依存 (S1C33用)
#

#
#  ターゲットアーキテクチャの定義
#
ARCH =

#
#  ディレクトリの定義
#
TOPDIR = /cygdrive/c/gnu33
LIBDIR = $(TOPDIR)/lib
INCDIR = $(TOPDIR)/include

#
#  コンパイラドライバの定義
#
CPP= $(TOPDIR)/cpp
CC= $(TOPDIR)/xgcc
AS= $(TOPDIR)/as
LD= $(TOPDIR)/ld
AR= $(TOPDIR)/ar
RM= $(TOPDIR)/rm
SED= $(TOPDIR)/sed
OBJDUMP= $(TOPDIR)/objdump
OBJCOPY= $(TOPDIR)/objcopy
RANLIB= ranlib
NM= nm

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)-$(TOOL) \
		 -I$(SRCDIR)/config/$(CPU) -I$(INCDIR)
COPTS := $(COPTS) -B$(TOPDIR)/ -gstabs -Wall -fno-common -O -mgda=0 -mlong-calls
LDFLAGS := $(LDFLAGS) -L$(LIBDIR)
LIBS := $(LIBS) -lc

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)-$(TOOL)
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o hw_serial.o sys.o lib.o

#
#  デフォルトコンパイルルールの定義
#
%.o: %.c
	$(CC) -c $(CFLAGS) $<

%.s: %.c
	$(CC) -S $(CFLAGS) $<

