#
#  Makefile のプロセッサ依存 (S1C33用)
#

#
#  ターゲットアーキテクチャの定義
#
ARCH = c33-epson-elf

#
#  ディレクトリの定義
#
TOPDIR = /usr/local/c33/
LIBDIR = $(TOPDIR)/lib/gcc-lib/c33-epson-elf/3.3.2/pe/
INCDIR = $(TOPDIR)/include

#
#  コンパイラドライバの定義
#
CPP= $(ARCH)-cpp
CC= $(ARCH)-gcc
AS= $(ARCH)-gcc
LD= $(ARCH)-ld
AR= $(ARCH)-ar
OBJDUMP= $(ARCH)-objdump
OBJCOPY= $(ARCH)-objcopy
RANLIB= ranlib
SED= sed
RM= rm
NM= nm

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)-$(TOOL) \
		 -I$(SRCDIR)/config/$(CPU) -I$(INCDIR)
COPTS := $(COPTS) -B$(TOPDIR)/ -gstabs -Wall -fno-common -O -mgda=0 -mlong-calls
LDFLAGS := $(LDFLAGS) -L$(LIBDIR)
LIBS := $(LIBS) -lc

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)-$(TOOL)
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o hw_serial.o sys.o lib.o

# <83>f<83>o<83>b<83>O<8e>x<89><87><8b>@<94>\<82>É<8a>Ö<82>·<82>é<92>è<8b>`
#
# !<92><8d><88>Ó!
#   WINFO_FLAG<8d>\<91>¢<91>Ì<82>Ì<92>è<8b>`<82>Íeventflag.c<93>à<82>É<82>Ä<8d>s<82>í<82>ê<82>Ä<82>¢<82>é<82>½<82>ß<81>A<8b>L<8f>q<88>Ê<92>u<82>ð
#   <91>¦<92>l<82>Å<8e>w<92>è<82>µ<81>A<92><8a><8f>o<82>µ<82>Ä<82>¢<82>é<81>B
#   <82>±<82>Ì<82>½<82>ß<81>A<83>x<81>[<83>X<82>Æ<82>È<82>éTOPPERS/JSP<82>ð<95>Ï<8d>X<82>µ<82>½<8f>ê<8d><87><82>Í<95>K<82>¸WINFO_FLAG<8d>\<91>¢<91>Ì
#   <82>Ì<8b>L<98>^<88>Ê<92>u<82>ð<8a>m<94>F<82>·<82>é<82>±<82>Æ<81>B
dbg_cmd.o : kernel_cfg.c $(CPU_DIR)-$(TOOL)/dbg_cmd.c
	$(RM) -f kernel_objs.h temp?
	$(SED) -e "1,74s/\(.*\)//" -e "89,9999s/.*//" $(KER_DIR)/eventflag.c > temp0
	$(SED) -e "/^$$/d" temp0 > temp1
	echo  >> temp1
	$(SED) -e "/_kernel_tmax_/s/^.*\(_kernel_tmax_[a-z]*\).*$$/#dxtern const ID \1;/" -e "/^[^#]/d" -e "/#[^d]/d" -e "/#define [^T]/d" -e "/^$$/d" kernel_cfg.c >> temp1

# _kernel_tmax_tskid<82>É<82>Â<82>¢<82>Ä<82>Ítask.h<82>Å<8b>L<8f>q<82>³<82>ê<82>Ä<82>¢<82>é<82>½<82>ß<8d>í<8f><9c><82>·<82>é<81>B
	$(SED) -e "s/#dxtern/extern/" -e "/tmax_tskid/d" -e "/TNUM_TSKID/d" temp1 > kernel_objs.h
	echo >> kernel_objs.h
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $(CPU_DIR)-$(TOOL)/dbg_cmd.c
	$(RM) kernel_objs.h temp?

dbg_mon.o : kernel_cfg.c $(CPU_DIR)-$(TOOL)/dbg_mon.c
	$(RM) -f kernel_objs.h temp?
	$(SED) -e "1,74s/\(.*\)//" -e "89,9999s/.*//" $(KER_DIR)/eventflag.c > temp0
	$(SED) -e "/^$$/d" temp0 > temp1
	echo  >> temp1
	$(SED) -e "/_kernel_tmax_/s/^.*\(_kernel_tmax_[a-z]*\).*$$/#dxtern const ID \1;/" \
		   -e "/_kernel_.*cb_table/s/^\(.*_kernel_.*cb_table\[.*\)/#dxtern \1/" \
		   -e "/_kernel_.*inib_table/s/^\(.*_kernel_.*inib_table\[.*\]\).*/#dxtern \1;/" \
		   -e "/__EMPTY_LABEL/s/__.*(\(.*\)\, \(_kernel_.*table\)).*/#dxtern \1 \2\[0\];/" \
		   -e "/^[^#]/d" -e "/#[^d]/d" -e "/#define [^T]/d" -e "/^$$/d" kernel_cfg.c >> temp1

# _kernel_tmax_tskid<82>É<82>Â<82>¢<82>Ä<82>Ítask.h<82>Å<8b>L<8f>q<82>³<82>ê<82>Ä<82>¢<82>é<82>½<82>ß<8d>í<8f><9c><82>·<82>é<81>B
	$(SED) -e "s/#dxtern/extern/" -e "/tmax_tskid/d" temp1 > kernel_objs.h
	echo >> kernel_objs.h
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $(CPU_DIR)-$(TOOL)/dbg_mon.c
	$(RM) kernel_objs.h temp?

dbg_wrap.o : $(CPU_DIR)-$(TOOL)/dbg_wrap.S
	$(CC) -c $(ASFLAGS) $<

dbg_mon_sub.o : $(CPU_DIR)-$(TOOL)/dbg_mon_sub.S
	$(CC) -c $(ASFLAGS) $<


#
#  デフォルトコンパイルルールの定義
#
%.o: %.c
	$(CC) -c $(CFLAGS) $<

%.s: %.c
	$(CC) -S $(CFLAGS) $<

