#!/bin/sh
# unzip the archives

ERROR()
{
  echo error: $*
  exit 1
}

USAGE()
{
  [ -z "$1" ] || echo error: $*
  echo usage: $(basename "$0") '<options> <directories>...'
  echo '       --help            -h         this message'
  echo '       --verbose         -v         show output'
  exit 1
}


# main program
# ------------

verbose=no
debug=no

unzippers='bz2:bunzip2 gz:gunzip'

getopt=/usr/local/bin/getopt
[ -x "${getopt}" ] || getopt=getopt
args=$(${getopt} -o hvd --long=help,verbose,debug -- "$@") || exit 1
# replace the arguments with the parsed values
eval set -- "${args}"

while :
do
  case "$1" in
    -v|--verbose)
      verbose=yes
      shift
      ;;

    -d|--debug)
      debug=yes
      shift
      ;;

    --)
      shift
      break
      ;;

    -h|--help)
      USAGE
      ;;

    *)
      USAGE invalid option: $1
      ;;
  esac
done

[ $# -le 0 ] && USAGE missing directory arguments

# check all elenents are directories
for dir in $*
do
  [ -d "${dir}" ] || USAGE not a directory: ${dir}
done

date_glob="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"

for dir in $*
do
  [ X"${verbose}" = X"yes" ] &&  echo directory: ${file}

  for zz in ${unzippers}
  do
    extension="${zz%%:*}"
    zz="${zz#*:}"
    program="${zz%%:*}"
    for file in "${dir}"/*."${extension}"
    do
      base="$(basename "${file}")"
      prefix="${base%%-*}"
      suffix="${base#*-${date_glob}-}"
      suffix="${suffix%*.${extension}}"
      for old_file in "${dir}/${prefix}-"${date_glob}"-${suffix}"
      do
        [ -f "${old_file}" ] || continue
        [ X"${verbose}" = X"yes" ] && echo delete: ${old_file}
        rm -f "${old_file}"
      done
      [ X"${verbose}" = X"yes" ] && echo run: ${program} "${file}"
      ${program} "${file}"
    done
  done
done

echo
echo completed
