"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Wikireader Update.py']
DATA_FILES = ['./tools/7za']
OPTIONS = {'argv_emulation': True,
 'iconfile': 'WikiReader.icns',
 'resources': 'images',
 'strip': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
