#
#  @(#) $Id: Makefile.config,v 1.2 2004/10/07 17:10:56 honda Exp $
# 

#
#  Makefile のシステム依存部分（サンプル）
#


#
#  ターゲットアーキテクチャの定義
#      powerpc-elf-gcc以外のコンパイラを用いる場合は
#      $(SYS)/Makefile.configで変数TARGETを定義する。
#　　　定義されていない場合は、デフォルトでTARGETに
#　　　powerpc-elfが設定される。
#
TARGET = powerpc-eabi


#
#  実行環境の定義
#
#      DBGENVには下記の中の１つだけを選択する。
#　　　どちらも選択しなければ、共通部でデフォルトの実行環境GDBが
#　　　選択される
#
#　　　ROM
#　　　　ROM化用の設定
#　　　　ROM化である（他の実行環境ではない）ことを明示しているだけで、
#　　　　ソースコード中で参照はしていない。

DBGENV = ROM

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)

#　デバッグオプションはgccのバージョンにより異なる場合があるので注意
COPTS := $(COPTS) -gdwarf -G 0 -msoft-float -mbig -meabi

# gccオプション 
#    -msoft-float  浮動小数点レジスタ・セットを使わない
#    -mbig         ビッグ・エンディアン
#    -N            .save'ファイルを作成しない
#    -meabi        「Embedded Applications Binary Interface (eabi)」に従う
#
# リンカ・オプション -N  
#     テキストセクションとデータセクションを読み書き可能に設定する.
#     また, データセグメントのページ境界への位置合わせをおこなわない. 

LDFLAGS := $(LDFLAGS) -N


#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o smc.o

#
#  マクロ定義オプション
#
CDEFS := $(CDEFS) -DIBM_PPC_EMB_ENV

#
#  各セグメントの開始アドレスの定義
#　　リンクスクリプト内で定義しても良い
#

# テキストセクションの先頭番地

#TEXT_START_ADDRESS=0x10002000

# dataセクションの先頭番地

DATA_START_ADDRESS=0x2000

#
#  リンカスクリプトの定義
#

LDSCRIPT = $(CPU)/$(SYS)/sample_elf.ld
