#
#  @(#) $Id: Makefile.config,v 1.4 2006/02/10 10:57:04 honda Exp $
# 

#
#  Makefile のシステム依存部分（Altera Stratix Professional Board 用）
# 


#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mno-hw-mul  
LIBS     := $(LIBS) -lc
LDFLAGS  := $(LDFLAGS) 

#
#  実行環境の定義
#
DBGENV := 

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o 

#
#  リンカスクリプトの定義
#
ifdef BOOT_ROM	
	LDSCRIPT = $(CPU)/$(SYS)/nios2elf_rom.l
else
	LDSCRIPT = $(CPU)/$(SYS)/nios2elf.l
endif



#
#  各セグメントの開始アドレスの定義
#
#TEXT_START_ADDRESS=0x0400
#DATA_START_ADDRESS=0x40000000






