#
#  @(#) $Id: Makefile.config,v 1.2 2007/05/21 01:33:50 honda Exp $
# 

#
#  Makefile のシステム依存部分（AZ9360 MB Board用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm9tdmi -Wa
LDFLAGS  := $(LDFLAGS) -mcpu=arm9tdmi  -N

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o ns9360.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/ns9360.ld


#
#  ターゲットボード依存の定義
#

#  AZ9360MB用
COPTS   := $(COPTS) -mbig-endian   
CDEFS   := $(CDEFS) -DAZ9360MB
LDFLAGS := $(LDFLAGS) -mbig-endian 
TEXT_START_ADDRESS=0x0000003c
#DATA_START_ADDRESS=0x000B0000
