#
#  @(#) $Id: Makefile.config,v 1.2 2007/05/08 07:47:39 honda Exp $
# 

#
#  Makefile のシステム依存部分（SUZAKU用）
#


#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS    := $(COPTS)
LDFLAGS  := $(LDFLAGS) 

#COPTS := $(COPTS) -mno-xl-soft-mul
COPTS  := $(COPTS) -mxl-soft-mul

#LIBS    := $(LIBS) -lc_soft


#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o 


#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x80000000   # 128KB
DATA_START_ADDRESS=0x80020000   # 128KB




