#
#  @(#) $Id: Makefile.config,v 1.3 2005/11/24 12:41:23 honda Exp $
# 

#
#	Makefile のターゲットシステム依存部（OAKS16用）
#

#
#  初期値
#
	# ISPの初期値(末尾の"h"は付けなくて良い)
RAMEND = 02c00
	#
MON = 0
	# RAMの先頭番地(SFRは含まない)
RAM_START_ADR = 00400
	# ROMの先頭番地
ROM_START_ADR = 0e0000

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)\config\$(CPU)-$(TOOL)\$(SYS) -I$(SRCDIR)\config\$(CPU)\$(SYS)
COPTS := $(COPTS) -g -O2
ASMFLAGS := $(ASMFLAGS) -O. -A -. -I.
KERNEL_ASMFLAGS := $(KERNEL_ASMFLAGS) -DRAMEND=$(RAMEND)h

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)\config\$(CPU)-$(TOOL)\$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) # sys_support.r30(使用していない)
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.r30

STASK_COBJS := $(STASK_COBJS) sfruart.r30

# ベクタテーブル定義ファイルの生成
m16cvec.inc: kernel_cfg.c
	$(CC) -E $(INCLUDES) $(<D)\$(<F) > kernel_cfg.i
	$(SRCDIR)\utils\m16c-renesas\m16cvec.exe -M0
